### ISSUE TITLE
Add Make trait

### ISSUE THREAD

**Issue by anowell** [willmtemple/golang#1]
Saw this [this post](http://sitr.us/2017/02/21/changes-i-would-make-to-go.html) and couldn't help but think that your crate should include that `Make` trait. Something like:

```rust
trait Make {
    fn make() -> Self;
}

impl <T> Make for Vec<T> {
    fn make() -> Vec<T> {
        Vec::new()
    }
}

impl <T> Make for (Sender<T>, Receiver<T>) {
    fn make() -> (Sender<T>, Receiver<T>) {
        channel()
    }
}

pub fn make<T: Make>() -> T {
    T::make()
}
```

**Comment by willmtemple** [comment]
I added this in the latest commit 7b2f25b9150f1357d055419eef91bbbe59253e8e

I will point out, though, that this is basically what Defaullt::default() does (for these types already).
